services:
  microservice-dev:
    build: .
    env_file: .env.dev
    expose:
      - "3000"

  microservice-prod:
    build: .
    env_file: .env.prod
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: loadbalancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - microservice-dev
      - microservice-prod
