version: "3.8"

services:
  app1:
    build: .
    container_name: micro1
    environment:
      - PORT=3000
    expose:
      - "3000"

  app2:
    build: .
    container_name: micro2
    environment:
      - PORT=3000
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: load_balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2

