version: '3.8'

services:
  app1:
    build: .
    container_name: microservice1
    environment:
      - NODE_ENV=production
      - HOSTNAME=app1
    expose:
      - "3000"

  app2:
    build: .
    container_name: microservice2
    environment:
      - NODE_ENV=production
      - HOSTNAME=app2
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: loadbalancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
